config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  resources :devices

  post "new_cart", to: "carts#create"
  delete "destroy_cart", to: "carts#destroy"

  devise_for :users, skip: :registrations
  as :user do
    get "users/edit", to: "devise/registrations#edit",
      as: "edit_user_registration"
    put "users", to: "devise/registrations#update", as: "user_registration"
  end

  resources :users, only: :show
  resources :messages
  resources :devices
  resources :borrow_devices

  namespace :admin do
   resources :borrow_devices
   resources :devices
  end

  mount ActionCable.server => "/cable"
end

app/models/borrow_device.rb
class BorrowDevice < ApplicationRecord

  after_initialize :set_defaults, unless: :persisted?

  enum borrow_status: [:reject, :waiting, :leader_accept, :borrowed, :return]

  has_many :borrow_items, dependent: :destroy

  belongs_to :user

  validates :borrow_date_from, presence: true
  validates :borrow_date_to, presence: true
  validates :status, presence: true,
    inclusion: {in: BorrowDevice.borrow_statuses.values}

  scope :find_by_user_id, -> user_id do
    BorrowDevice.where(user_id: user_id).order(created_at: :desc)
  end

  scope :list_borrowed_in_group, -> group_id do
    BorrowDevice.where(user_id: User.list_user_id_by_group(group_id))
      .order(created_at: :desc)
  end

  scope :list_borrowed_in_workspace, -> workspace_id do
    BorrowDevice.where(user_id: User.list_user_id_by_workspace(workspace_id))
      .order(created_at: :desc)
  end

  scope :get_all, -> do
    BorrowDevice.all.order(created_at: :desc)
  end

  scope :dealine_borrow, -> do
    where borrow_date_to: Date.today,
    status: BorrowDevice.borrow_statuses[:borrowed]
  end

  private
  def set_defaults
    self.borrow_type ||= false
  end

  def self.send_deline_borrow
    borrows = self.dealine_borrow
      if borrows
      borrows.each do |borrow|
        user = borrow.user
        UserMailer.send_email_deadline_to_user(user).deliver
      end
    end
  end
end

app/controllers/admin/borrow_devices_controller.rb
class Admin::BorrowDevicesController < Admin::BaseController
  include BorrowDevicesHelper
  load_and_authorize_resource except: :create
  before_action :load_borrow_device, only: [:show, :edit]

  def new
    @borrow_device = BorrowDevice.new
    devices = get_list_devices
    return if devices.present?
    flash[:errors] = t "borrow_device.device_not_found"
    redirect_to admin_borrow_devices_path
  end

  def index
    case current_user.position
    when User.user_positions[:leader]
      @borrowed_devices = BorrowDevice
        .list_borrowed_in_group(current_user.group_id)
        .page(params[:page]).per Settings.view.borrow_device.per_page
    when User.user_positions[:bo]
      @borrowed_devices = BorrowDevice
        .list_borrowed_in_workspace(current_user.group.workspace_id)
        .page(params[:page]).per Settings.view.borrow_device.per_page
    when User.user_positions[:admin]
      @borrowed_devices = BorrowDevice.get_all
        .page(params[:page]).per Settings.view.borrow_device.per_page
    end
    return if @borrowed_devices.present?
    flash[:errors] = t "borrow_device.device_not_found"
    redirect_to root_path
  end

  def create
    authorize! :create, @borrow_device
    @borrow_device = BorrowDevice.new borrow_device_params
    devices = get_list_devices
    if devices.present?
      flag = false
      if check_date_borrow
        flag = create_new_borrow @borrow_device, devices
        if flag
          session.delete(:item)
          flash[:success] = t "borrow_device.congratulations"
          redirect_to admin_borrow_devices_path
        else
          flash[:errors] = t "borrow_device.create_failed"
          redirect_to new_admin_borrow_device_path
        end
      else
        get_list_devices
        render :new
      end
    else
      flash[:errors] = t "borrow_device.device_not_found"
      redirect_to devices_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @borrow_device = BorrowDevice.find_by id: params[:id]
    if @borrow_device.present?
      flag = false
      if params[:borrow_device][:status].present? &&
        @borrow_device.status != BorrowDevice.borrow_statuses[:reject]
        @borrow_device.status = params[:borrow_device][:status].to_i
        flag = update_borrow @borrow_device
        create_notification current_user.position, @borrow_device
        if flag
          flash[:success] = t "borrow_device.updated"
        else
          flash[:errors] = t "borrow_device.update_failed"
        end
      else
        flash[:errors] = t "borrow_device.cant_update"
      end
    else
      flash[:errors] = t "borrow_device.borrow_not_found"
    end
    redirect_to admin_borrow_devices_path
  end

  private
  def borrow_device_params
    params.require(:borrow_device).permit :user_id, :borrow_date_from,
      :borrow_date_to, :status, :borrow_type
  end

  def load_borrow_device
    @borrowed_device = BorrowDevice.find_by id: params[:id]
      if @borrowed_device.present?
      @borrowed_items = @borrowed_device.borrow_items
      return if @borrowed_items.present?
      flash[:errors] = t "borrow_device.device_not_found"
    else
      flash[:errors] = t "borrow_device.borrow_not_found"
    end
    redirect_to admin_borrow_devices_path
  end

  def create_only_notification user_id, activity, notifications, link
    Notification.create( user_id: user_id, activity: activity,
      notifications: notifications, link: link)
  end

  def create_notification user_position, borrow_device
    if borrow_device.status == BorrowDevice.borrow_statuses[:reject]
      case current_user.position
      when User.user_positions[:leader]
        position = t "borrow_device.group_noti"
      when User.user_positions[:bo]
        position = t "borrow_device.bo_noti"
      end
      create_only_notification borrow_device.user_id,
        t("borrow_device.notification_reject"),
        t("borrow_device.reject_message", pos: position,
        name: current_user.username),
        "#{borrow_devices_path}"
    else
      case user_position
      when User.user_positions[:leader]
        workspace = borrow_device.user.group.workspace.users
          .get_manager(User.user_positions[:bo])
        create_only_notification workspace[0]["id"],
          t("borrow_device.notification_update"),
          t("borrow_device.update_message", pos: t("borrow_device.group_noti"),
          name: current_user.username),
          "#{edit_admin_borrow_device_path(borrow_device)}"
        create_only_notification borrow_device.user_id,
          t("borrow_device.notification_update"),
          t("borrow_device.update_message", pos: t("borrow_device.group_noti"),
          name: current_user.username),
           "#{borrow_devices_path}"
      when User.user_positions[:bo]
        create_only_notification borrow_device.user_id,
          t("borrow_device.notification_update"),
          t("borrow_device.update_message", pos: t("borrow_device.bo_noti"),
          name: current_user.username),
          "#{borrow_devices_path}"
      end
    end
  end

end

app/controllers/borrow_devices_controller.rb
class BorrowDevicesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @borrowed_devices = BorrowDevice.find_by_user_id(current_user.id)
      .page(params[:page]).per Settings.view.borrow_device.per_page
    return if @borrowed_devices.present?
    flash[:errors] = t "borrow_device.borrow_not_found"
    redirect_to root_path
  end

  def new
    @borrow_device = BorrowDevice.new
    devices = get_list_devices
    return if devices.present?
    flash[:errors] = t "borrow_device.device_not_found"
    redirect_to devices_path
  end

  def create
    borrow_device = BorrowDevice.new borrow_device_params
    devices = get_list_devices
    flag = false
    if devices.present?
      if check_date_borrow == true
        Device.transaction do
          BorrowItem.transaction do
            BorrowDevice.transaction do
              raise ActiveRecord::Rollback unless borrow_device.save
              devices.each do |device|
                if !device.borrowed
                  borrowed_item = BorrowItem.new_borrow_item(device.id,
                    borrow_device.id)
                  raise ActiveRecord::Rollback unless borrowed_item.save
                else
                  delete_device_in_item device.id
                  raise ActiveRecord::Rollback
                end
              end
              devices.each do |device|
                raise ActiveRecord::Rollback unless device
                  .update_attributes(borrowed: true)
              end
              flag = true
            end
          end
        end
        if flag
          create_notification t("borrow_device.notification_borrow")
          session.delete(:item)
          flash[:success] = t "borrow_device.congratulations"
          redirect_to borrow_devices_path
        else
          flash[:errors] = t "borrow_device.create_failed"
          redirect_to new_borrow_device_path
        end
      else
        get_list_devices
        flash[:errors] = t "borrow_device.date_invalid"
        redirect_to new_borrow_device_path
      end
    else
      flash[:errors] = t "borrow_device.device_not_found"
      redirect_to devices_path
    end
  end

  def edit
    @borrow_device = BorrowDevice.find_by id: params[:id]
    return if @borrow_device.present?
    flash[:errors] = t "borrow_device.device_not_found"
    redirect_to borrow_devices_path
  end

  def show
    @borrowed_device = BorrowDevice.find_by id: params[:id]
    if @borrowed_device.present?
      @borrowed_items = BorrowItem.get_list_item_by_borrow_id params[:id]
      return if @borrowed_items.present?
      flash[:errors] = t "borrow_device.item_not_found"
      redirect_to borrow_devices_path
    else
      flash[:errors] = t "borrow_device.borrow_not_found"
      borrow_devices_path
    end
  end

  def update
    borrow_device = BorrowDevice.find_by id: params[:id]
    if borrow_device.present?
      flag = false
      borrow_device.status = BorrowDevice.borrow_statuses[:reject]
      BorrowDevice.transaction do
        Device.transaction do
          borrow_device.borrow_items.each do |item|
            device = item.device
            device.borrowed = false
            raise ActiveRecord::Rollback unless device.save
          end
          raise ActiveRecord::Rollback unless borrow_device.save
          flag = true
        end
      end
      if flag
        create_notification t("borrow_device.notification_reject")
        flash[:success] = t "borrow_device.updated"
      else
        flash[:success] = t "borrow_device.update_failed"
      end
    else
      flash[:errors] = t "borrow_device.borrow_not_found"
    end
    redirect_to borrow_devices_path
  end

  private

  def check_date_borrow
    date_from = params[:borrow_device][:borrow_date_from]
    date_to = params[:borrow_device][:borrow_date_to]
    if date_from.present? && date_to.present?
      return Date.parse(date_from) < Date.parse(date_to)
    else
      false
    end
  end

  def borrow_device_params
    params.require(:borrow_device).permit :user_id, :borrow_date_from,
      :borrow_date_to, :status
  end

  def create_notification noti
    @group = current_user.group
    @group.users.get_manager(User.user_positions[:leader]).each do |user|
      Notification.create(user_id: user.id, activity: noti,
        notifications: t("borrow_device.noti_message",
        name: current_user.username, state: noti),
        link: "#{admin_borrow_devices_path}")
    end
  end
end

app/helpers/borrow_devices_helper.rb
module BorrowDevicesHelper
  def check_over_time borrow_device
    now = DateTime.now.to_date
    now > borrow_device.borrow_date_to.to_date ? true : false
  end

  def get_borrow_status status
    case status
    when BorrowDevice.borrow_statuses[:reject]
      t "borrow_device.reject_status"
    when BorrowDevice.borrow_statuses[:waiting]
      t "borrow_device.member"
    when BorrowDevice.borrow_statuses[:leader_accept]
      t "borrow_device.leader"
    when BorrowDevice.borrow_statuses[:borrowed]
      t "borrow_device.borrowed"
    else
      t "borrow_device.return"
    end
  end

  def get_borrow_status_value status
    case current_user.position
    when User.user_positions[:leader]
      BorrowDevice.borrow_statuses[:leader_accept]
    when User.user_positions[:bo]
      if status == BorrowDevice.borrow_statuses[:leader_accept]
        BorrowDevice.borrow_statuses[:borrowed]
      elsif status == BorrowDevice.borrow_statuses[:borrowed]
        BorrowDevice.borrow_statuses[:return]
      end
    end
  end

  def get_lable_borrow_update status
    case status
    when BorrowDevice.borrow_statuses[:member]
      t "borrow_device.btn_accept"
    when BorrowDevice.borrow_statuses[:leader_accept]
      t "borrow_device.btn_borrow"
    when BorrowDevice.borrow_statuses[:borrowed]
      t "borrow_device.btn_return"
    end
  end

  def update_borrow borrow_device
    result = true
    BorrowDevice.transaction do
      if borrow_device.save
        if borrow_device.status == BorrowDevice.borrow_statuses[:return] ||
          borrow_device.status == BorrowDevice.borrow_statuses[:reject]
          result = set_device_return borrow_device.borrow_items
          raise ActiveRecord::Rollback unless result
        end
      end
    end
    result
  end

  def set_device_return borrow_items
    flag = false
    Device.transaction do
      borrow_items.each do |item|
        device = item.device
        device.borrowed = false
        raise ActiveRecord::Rollback unless device.save
      end
      flag = true
    end
    flag
  end

  def check_date_borrow
    date_from = params[:borrow_device][:borrow_date_from]
    date_to = params[:borrow_device][:borrow_date_to]
    if date_from.present? && date_to.present?
      return Date.parse(date_from) < Date.parse(date_to)
    else
      false
    end
  end

  def create_new_borrow borrow_device, devices
    flag = false
    Device.transaction do
      BorrowItem.transaction do
        BorrowDevice.transaction do
          raise ActiveRecord::Rollback unless borrow_device.save
          devices.each do |device|
            if !device.borrowed
              borrow_item = BorrowItem.new_borrow_item(device.id,
                borrow_device.id)
              raise ActiveRecord::Rollback unless borrow_item.save
            else
              delete_device_in_item device.id
              raise ActiveRecord::Rollback
            end
          end
          devices.each do |device|
            raise ActiveRecord::Rollback unless device
              .update_attributes(borrowed: true)
          end
          flag = true
        end
      end
    end
    flag
  end

end

app/views/borrow_devices/_borrowed_device.html.erb
<tr class="<%= "red" if check_over_time borrowed_device %>">
  <td><%= get_index borrowed_device_counter %></td>
  <td>
    <b><%= borrowed_device.created_at.to_formatted_s(:long) %></b>
  </td>
  <td>
    <b><%= borrowed_device.borrow_date_to.to_formatted_s(:long) %></b>
  </td>
  <td>
    <b><%= get_borrow_status borrowed_device.status %></b>
  </td>
  <td>
    <%= link_to borrow_device_path(borrowed_device.id) do %>
      <span class="glyphicon glyphicon-eye-open"></span>
    <% end -%>
    <% if can? :update, borrowed_device %>
      <%= link_to t("borrow_device.btn_reject"),
        borrow_device_path(borrowed_device.id), method: :put,
        data: {confirm: t("device.confirm-delete",
        name: borrowed_device.id)} %>
    <% end -%>
  </td>
</tr>

app/views/borrow_devices/_list_borrowed_item.html.erb
<tr>
  <td><%= get_index list_borrowed_item_counter %></td>
  <td>
    <b>
      <%= link_to list_borrowed_item.device.id,
        device_path(list_borrowed_item.device.id) %>
    </b>
  </td>
  <td>
    <b>
      <%= link_to list_borrowed_item.device.name,
        device_path(list_borrowed_item.device.id) %>
    </b>
  </td>
  <td>
    <div class="td_small">
      <%= link_to device_path(list_borrowed_item.device.id) do %>
        <%= image_tag list_borrowed_item.device.thumnail,
          class: "cart_image" %>
      <% end %>
    </div>
  </td>
</tr>

app/views/borrow_devices/index.html.erb
<div class="container borrowed-devices">
  <h3><%= t "borrow_device.list_borrowed" %></h3>
  <div class="borrowed-items">
    <%= paginate @borrowed_devices %>
    <table class="table">
      <tr>
        <th><%= t "borrowed_device.index" %></th>
        <th><%= t "borrowed_device.date_from" %></th>
        <th><%= t "borrowed_device.date_to" %></th>
        <th><%= t "borrowed_device.status" %></th>
        <th colspan="2"></th>
      </tr>
      <% if @borrowed_devices.present? %>
        <%= render partial: "borrowed_device", collection: @borrowed_devices %>
      <% end -%>
    </table>
    <%= paginate @borrowed_devices %>
  </div>
</div>

app/views/borrow_devices/new.html.erb
<div class="borrow-device-form">
  <div class="title">
    <h3><%= t "borrow_device.title" %></h3>
  </div>
  <div class="list-borrowed">
    <%= render "layouts/cart" %>
  </div>
  <div class="form">
    <%= form_for @borrow_device do |f| %>

      <div class="td_small">
        <%= image_tag current_user.avatar? ? current_user.avatar
          : Settings.view.user.default_avatar, class: "cart_image" %>
      </div>
      <br/>

      <%= f.label t "borrow_device.name" %>
      <%= f.label :username, current_user.username, class: "form-control" %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <br/>

      <%= f.label t "borrow_device.email" %>
      <%= f.label :username, current_user.email, class: "form-control" %>
      <br/>

      <%= f.label t("borrow_device.date_borrow") %>
      <br/>
      <%= f.text_field :borrow_date_from, class: "date_from", readonly: true,
        data: {provide: :datepicker} %>
      <span><%= t "borrow_device.to" %></span>
      <%= f.text_field :borrow_date_to, class: "date_to", readonly: true,
        data: {provide: :datepicker} %>

      <%= f.hidden_field :status,
        value: BorrowDevice.borrow_statuses[:waiting] %>
      <br/>

      <%= f.submit t("borrow_device.checkout"), class: "btn btn-primary" %>
    <% end -%>
  </div>
</div>

app/views/borrow_devices/show.html.erb
<div class="borrow-details">
  <div class="title">
    <h3>
      <%= t "borrow_device.list_device" %><%= @borrowed_device.id %>
    </h3>
  </div>
  <div class="tbl-borrowed-items">
    <table class="table">
      <tr>
        <th><%= t "borrowed_device.index" %></th>
        <th><%= t "device.id_device" %></th>
        <th><%= t "device.name_device" %></th>
        <th><%= t "borrowed_device.image" %></th>
      </tr>
      <% if @borrowed_items.present? %>
        <%= render partial: "list_borrowed_item",
          collection: @borrowed_items %>
      <% end -%>
    </table>
    <div>
      <b><%= t "borrow_device.status" %></b>
      <i><%= get_borrow_status @borrowed_device.status %></i>
    </div>
  </div>
</div>