config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  resources :devices

  post "new_cart", to: "carts#create"
  delete "destroy_cart", to: "carts#destroy"

  devise_for :users, skip: :registrations
  as :user do
    get "users/edit", to: "devise/registrations#edit",
      as: "edit_user_registration"
    put "users", to: "devise/registrations#update", as: "user_registration"
  end

  resources :users, only: :show
  resources :messages
  resources :devices
  resources :borrow_devices

  namespace :admin do
   resources :borrow_devices
   resources :devices
  end

  mount ActionCable.server => "/cable"
end

app/models/device.rb
class Device < ApplicationRecord

  mount_uploader :thumnail, ThumnailUploader

  after_initialize :set_defaults, unless: :persisted?

  has_many :borrow_items, dependent: :destroy

  belongs_to :category
  belongs_to :workspace

  validates_presence_of :thumnail
  validates :name, presence: true
  validates :informations, presence: true
  validates :workspace_id, presence: true
  validates :category_id, presence: true

  scope :get_all_devices, -> do
    Device.all.order(borrowed: :asc)
  end

  scope :get_devices_by_category, -> category_id do
    where(category_id: category_id)
  end

  scope :get_devices_by_ids, -> ids do
    where(id: ids)
  end

  scope :get_devices_by_workspace, -> workspace_id do
    where(workspace_id: workspace_id)
  end

  class << self
    def import file
      spreadsheet = open_spreadsheet file
      header = spreadsheet.row(1)
      if check_valid_header header
        arr_failed = []
        (2..spreadsheet.last_row).each do |i|
          row = Hash[[header, spreadsheet.row(i)].transpose]
          device = find_or_initialize_by id: row["id"]
          device_attribute = row.to_hash
          device_attribute["thumnail"] = File.open(device_attribute["thumnail"])
          device.attributes = device_attribute
          if device.valid?
            device.update_attributes! device_attribute
          else
            arr_failed << i
          end
        end
        arr_failed
      end
    end

    def open_spreadsheet file
      case File.extname file.original_filename
      when ".csv" then Roo::Csv.new(file.path, file_warning: :ignore)
      when ".xls" then Roo::Excel.new(file.path, file_warning: :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, file_warning: :ignore)
      else raise t "device.unknown_file"
      end
    end

    def check_valid_header arr_attribute
      result = true
      arr_attribute.each do |key|
        unless Device.column_names.include?(key)
          result = false
        end
      end
      result
    end

    def to_csv
    attributes = %w{id name informations status workspace_id category_id}
      CSV.generate(headers: true) do |csv|
        csv << attributes
        all.each do |device|
          csv << device.attributes.values_at(*attributes)
        end
      end
    end
  end

  private
  def set_defaults
    self.borrowed ||= false
  end

end

app/controllers/admin/devices_controller.rb
class Admin::DevicesController < Admin::BaseController
  load_and_authorize_resource except: :create
  before_action :load_device, only: [:edit, :update, :destroy]

  def index
    if verify_admin current_user
      if params[:fitter].present?
        @devices = Device.get_devices_by_workspace params[:fitter]
          .page(params[:page]).per Settings.view.device.per_page
      else
        @devices = Device.all
          .page(params[:page]).per Settings.view.device.per_page
      end
    else
      @devices = Device.get_devices_by_workspace(current_user
        .group.workspace_id)
        .page(params[:page]).per Settings.view.device.per_page
    end
    if @devices.present?
      respond_to do |format|
        format.html
        format.js
        format.xls {send_data @devices.to_csv}
      end
    else
      flash[:warning] = t "device.device_not_found"
      redirect_to root_path
    end
  end

  def new
    @device = Device.new
    @base_support = Supports::BaseSupport.new
  end

  def create
    authorize! :create, @device
    if params[:import]
      if params[:import_file].present?
        import params[:import_file]
      else
        flash[:errors] = t "device.file_not_found"
        redirect_to new_admin_device_path
      end
    else
      @device = Device.new device_params
      if @device.save
        flash[:success] = t "device.created"
        redirect_to admin_devices_path
      else
        render :new
      end
    end
  end

  def edit
    @base_support = Supports::BaseSupport.new
  end

  def update
    if @device.update_attributes device_params
      flash[:success] = t "device.updated"
    else
      flash[:errors] = t "device.update_failed"
    end
    redirect_to admin_devices_path
  end

  def destroy
    if @device.destroy
      flash[:success] = t "device.deleted"
    else
      flash[:errors] = t "device.delete_failed"
    end
    redirect_to admin_devices_path
  end


  private
  def device_params
    params.require(:device).permit :name, :thumnail, :informations, :status,
      :category_id, :workspace_id
  end

  def load_device
    @device = Device.find_by id: params[:id]
    unless @device.present?
      flash[:warning] = t "device.device_not_found"
      redirect_to admin_devices_path
    end
  end

  def import file
    arr_failed = Device.import file
    if arr_failed.nil?
      flash[:errors] = t "device.import_header_failed"
      redirect_to new_admin_device_path
    elsif arr_failed.blank?
      flash[:success] = t "device.imported"
      redirect_to admin_devices_path
    else
      flash[:errors] = t("device.imported_failed", id: arr_failed)
      redirect_to admin_devices_path
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  def index
    if params[:category_id].present?
      device_all = Device.get_devices_by_category params[:category_id]
    else
      device_all = Device.get_devices_by_workspace(current_user
        .group.workspace_id)
    end
    @search = device_all.search params[:q]
    @devices = @search.result
      .page(params[:page]).per Settings.view.device.per_page
    @base_support = Supports::BaseSupport.new
    return if @devices.present?
    flash[:errors] = t "device.device_not_found"
    redirect_to devices_path
  end

  def show
    @device = Device.find_by id: params[:id]
    return if @devices.present?
    flash[:errors] = t "device.device_not_found"
    redirect_to devices_path
  end

end

app/helpers/devices_helper.rb
module DevicesHelper

  def get_borrowed borrowed
    if borrowed
      t "device.borrowed"
    else
      t "device.not_yet_borrowed"
    end
  end

  def get_index index
    index += Settings.view.increase_index
  end

  def verify_admin user
    user.position == User.user_positions[:admin] ? true : false
  end

end

app/views/devices/_add_devices_borrowed.html.erb
<%= form_tag new_cart_path, remote: true do %>
  <div class="btn-borrow"">
    <div class="input-group-btn">
      <%= hidden_field_tag :device_id, device.id %>
      <%= submit_tag I18n.t("device.btn_borrow"),
        class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/devices/_category.html.erb
<li>
  <%= link_to category.name, devices_path(category_id: category.id),
    class: "category-link" %>
</li>

app/views/devices/_device.html.erb
<li class="device-item">
  <div class="item">
    <div class="img-item">
      <%= link_to device_path(device.id) do %>
        <%= image_tag device.thumnail, class: "img-response" %>
      <% end -%>
      <div class="information">
        <p class="more-information"><%= truncate(device.informations,
          length: Settings.view.device.information_length,
          linmission: t("device.ellipsestext")) %>
          <%= link_to t("device.show_more"), device_path(device.id) %>
        </p>
      </div>
    </div>
    <div class="item-name">
      <h3><%= link_to device.name, device_path(device.id) %></h3>
    </div>

    <div class="borrow">
      <p><%= t "device.borrow" %><%= get_borrowed(device.borrowed) %></p>
    </div>
    <% unless device.borrowed %>
      <div>
        <%= render "add_devices_borrowed", device: device %>
      </div>
    <% end -%>
  </div>
</li>

app/views/devices/_list_devices.html.erb
<ul>
  <%= render partial: "device", collection: @devices %>
</ul>

app/views/devices/index.html.erb
<div class="container list-devices">
  <div class="row">
    <div class="col-md-3">
      <div class="categories">
        <ul>
          <li>
            <%= link_to t("device.category"), "#",
              class: "active category-link" %>
          </li>
          <% if @base_support.get_categories.present? %>
            <%= render partial: "category",
              collection: @base_support.get_categories %>
          <% end -%>
        </ul>
      </div>
      <div class="list-borrowed">
        <%= render "layouts/cart" %>
      </div>
      <%= link_to t("device.botrrow_device"), new_borrow_device_path,
        class: "btn btn-primary book-devices" %>
    </div>
    <div class="col-md-9">
      <div class="search-item">
        <%= search_form_for @search do |f| %>
          <div class="field">
            <%= f.text_field :name_cont, placeholder: t("device.device_name") %>
            <%= f.check_box(:borrowed_eq, {}, false, nil) %>
 -          <%= f.label :borrowed_eq, t("device.not_borrowed") %><br>
          </div>
          <div class="actions"><%= f.submit t("device.search") %></div>
        <% end %>
      </div>
      <div class="show-list">
        <%= paginate @devices %>
        <%= render "list_devices" %>
        <%= paginate @devices %>
      </div>
    </div>
  </div>
</div>

app/views/devices/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="device-img">
        <%= image_tag @device.thumnail, class: "img-response" %>
      </div>
    </div>
    <div class="col-md-8">
      <div class="device-name">
        <h2><%= @device.name %></h2>
        <hr/>
      </div>
      <div class="information">
        <p><%= @device.informations %></p>
      </div>
      <div class="status">
        <p><%= t "device.status" %><%= @device.status %></p>
      </div>
      <div class="borrow">
        <p><%= t "device.borrow" %><%= get_borrowed(@device.borrowed) %></p>
      </div>
      <% unless @device.borrowed %>
        <div class="btn-borrow">
          <%= link_to t("device.btn_borrow"), "#",
            class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>