config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  resources :devices

  post "new_cart", to: "carts#create"
  delete "destroy_cart", to: "carts#destroy"

  devise_for :users, skip: :registrations
  as :user do
    get "users/edit", to: "devise/registrations#edit",
      as: "edit_user_registration"
    put "users", to: "devise/registrations#update", as: "user_registration"
  end

  resources :users, only: :show
  resources :messages
  resources :devices
  resources :borrow_devices

  namespace :admin do
   resources :borrow_devices
   resources :devices
  end

  mount ActionCable.server => "/cable"
end

app/models/device.rb
class Device < ApplicationRecord

  mount_uploader :thumnail, ThumnailUploader

  after_initialize :set_defaults, unless: :persisted?

  has_many :borrow_items, dependent: :destroy

  belongs_to :category
  belongs_to :workspace

  validates_presence_of :thumnail
  validates :name, presence: true
  validates :informations, presence: true
  validates :workspace_id, presence: true
  validates :category_id, presence: true

  scope :get_all_devices, -> do
    Device.all.order(borrowed: :asc)
  end

  scope :get_devices_by_category, -> category_id do
    where(category_id: category_id)
  end

  scope :get_devices_by_ids, -> ids do
    where(id: ids)
  end

  scope :get_devices_by_workspace, -> workspace_id do
    where(workspace_id: workspace_id)
  end

  class << self
    def import file
      spreadsheet = open_spreadsheet file
      header = spreadsheet.row(1)
      if check_valid_header header
        arr_failed = []
        (2..spreadsheet.last_row).each do |i|
          row = Hash[[header, spreadsheet.row(i)].transpose]
          device = find_or_initialize_by id: row["id"]
          device_attribute = row.to_hash
          device_attribute["thumnail"] = File.open(device_attribute["thumnail"])
          device.attributes = device_attribute
          if device.valid?
            device.update_attributes! device_attribute
          else
            arr_failed << i
          end
        end
        arr_failed
      end
    end

    def open_spreadsheet file
      case File.extname file.original_filename
      when ".csv" then Roo::Csv.new(file.path, file_warning: :ignore)
      when ".xls" then Roo::Excel.new(file.path, file_warning: :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, file_warning: :ignore)
      else raise t "device.unknown_file"
      end
    end

    def check_valid_header arr_attribute
      result = true
      arr_attribute.each do |key|
        unless Device.column_names.include?(key)
          result = false
        end
      end
      result
    end

    def to_csv
    attributes = %w{id name informations status workspace_id category_id}
      CSV.generate(headers: true) do |csv|
        csv << attributes
        all.each do |device|
          csv << device.attributes.values_at(*attributes)
        end
      end
    end
  end

  private
  def set_defaults
    self.borrowed ||= false
  end

end

app/controllers/admin/devices_controller.rb
class Admin::DevicesController < Admin::BaseController
  load_and_authorize_resource except: :create
  before_action :load_device, only: [:edit, :update, :destroy]

  def index
    if verify_admin current_user
      if params[:fitter].present?
        @devices = Device.get_devices_by_workspace params[:fitter]
          .page(params[:page]).per Settings.view.device.per_page
      else
        @devices = Device.all
          .page(params[:page]).per Settings.view.device.per_page
      end
    else
      @devices = Device.get_devices_by_workspace(current_user
        .group.workspace_id)
        .page(params[:page]).per Settings.view.device.per_page
    end
    if @devices.present?
      respond_to do |format|
        format.html
        format.js
        format.xls {send_data @devices.to_csv}
      end
    else
      flash[:warning] = t "device.device_not_found"
      redirect_to root_path
    end
  end

  def new
    @device = Device.new
    @base_support = Supports::BaseSupport.new
  end

  def create
    authorize! :create, @device
    if params[:import]
      if params[:import_file].present?
        import params[:import_file]
      else
        flash[:errors] = t "device.file_not_found"
        redirect_to new_admin_device_path
      end
    else
      @device = Device.new device_params
      if @device.save
        flash[:success] = t "device.created"
        redirect_to admin_devices_path
      else
        render :new
      end
    end
  end

  def edit
    @base_support = Supports::BaseSupport.new
  end

  def update
    if @device.update_attributes device_params
      flash[:success] = t "device.updated"
    else
      flash[:errors] = t "device.update_failed"
    end
    redirect_to admin_devices_path
  end

  def destroy
    if @device.destroy
      flash[:success] = t "device.deleted"
    else
      flash[:errors] = t "device.delete_failed"
    end
    redirect_to admin_devices_path
  end


  private
  def device_params
    params.require(:device).permit :name, :thumnail, :informations, :status,
      :category_id, :workspace_id
  end

  def load_device
    @device = Device.find_by id: params[:id]
    unless @device.present?
      flash[:warning] = t "device.device_not_found"
      redirect_to admin_devices_path
    end
  end

  def import file
    arr_failed = Device.import file
    if arr_failed.nil?
      flash[:errors] = t "device.import_header_failed"
      redirect_to new_admin_device_path
    elsif arr_failed.blank?
      flash[:success] = t "device.imported"
      redirect_to admin_devices_path
    else
      flash[:errors] = t("device.imported_failed", id: arr_failed)
      redirect_to admin_devices_path
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  def index
    if params[:category_id].present?
      device_all = Device.get_devices_by_category params[:category_id]
    else
      device_all = Device.get_devices_by_workspace(current_user
        .group.workspace_id)
    end
    @search = device_all.search params[:q]
    @devices = @search.result
      .page(params[:page]).per Settings.view.device.per_page
    @base_support = Supports::BaseSupport.new
    return if @devices.present?
    flash[:errors] = t "device.device_not_found"
    redirect_to devices_path
  end

  def show
    @device = Device.find_by id: params[:id]
    return if @devices.present?
    flash[:errors] = t "device.device_not_found"
    redirect_to devices_path
  end

end

app/helpers/devices_helper.rb
module DevicesHelper

  def get_borrowed borrowed
    if borrowed
      t "device.borrowed"
    else
      t "device.not_yet_borrowed"
    end
  end

  def get_index index
    index += Settings.view.increase_index
  end

  def verify_admin user
    user.position == User.user_positions[:admin] ? true : false
  end

end

app/views/admin/devices/_device.html.erb
<tr>
  <td>
    <b><%= device.id %></b>
  </td>
  <td>
    <b><%= device.name %></b>
  </td>
  <td>
    <%= link_to edit_admin_device_path(device.id) do %>
      <%= image_tag device.thumnail, class: "img-responsive device_image" %>
    <% end -%>
  </td>
  <td>
    <p class="borrow_<%= device.borrowed %>">
      <%= get_borrowed device.borrowed %>
    </p>
  </td>
  <% unless device.borrowed %>
    <td>
      <% if can? :update, @device %>
        <%= link_to edit_admin_device_path(device.id) do %>
          <span class="glyphicon glyphicon-edit"></span>
        <% end -%>
      <% end %>
    </td>
    <td>
      <% if can? :destroy, @device %>
        <%= link_to admin_device_path(device.id), method: :delete,
          data: {confirm: t("device.confirm-delete", name: device.name)} do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end -%>
      <% end %>
    </td>
  <% end -%>
</tr>

app/views/admin/devices/_list_devices.html.erb
<table class="table">
  <tr>
    <th><%= t "device.id_device" %></th>
    <th><%= t "device.name_device" %></th>
    <th><%= t "device.thumnail" %></th>
    <th><%= t "device.borrowed" %></th>
    <th colspan="2"></th>
  </tr>
  <% if @devices.present? %>
    <%= render partial: "device", collection: @devices %>
  <% end -%>
</table>
<%= paginate @devices %>

app/views/admin/devices/edit.html.erb
<div class="admin-update-device">
  <h3><%= t "device.update_device_title" %></h3>
  <div class="update-device">
    <%= simple_form_for [:admin, @device], wrapper: :horizontal_form,
      html: {class: "new-device"} do |f| %>

      <%= f.input :name, label: t("device.device_name"),
        input_html: {class: "form-control"} %>

      <%= f.input :informations, input_html: {class: "form-control"} %>

      <%= f.input :status, input_html: {class: "form-control"} %>

      <% if current_user.position == User.user_positions[:admin] %>
        <%= f.input :workspace_id, collection: @base_support.get_workspaces,
          label_method: :name, value_method: :id, include_blank: false,
          label: t("device.workspace"),
          input_html: {class: "form-control"} %>
      <% else %>
        <%= f.hidden_field :workspace_id,
          value: current_user.group.workspace_id,
          input_html: {class: "form-control"} %>
      <% end -%>

      <%= f.input :category_id, collection: @base_support.get_categories,
        label_method: :name, value_method: :id, include_blank: false,
        label: t("device.category"), input_html: {class: "form-control"} %>

      <%= image_tag @device.thumnail, class: "update-device-thumnail" %>

      <%= f.input :thumnail, as: :file, label: t("device.image") %>

      <%= f.button :submit, t("device.btn_update_device"),
        class: "btn btn-primary" %>

    <% end -%>
  </div>
</div>

app/views/admin/devices/index.html.erb
<% provide :pagetext, t("device.devices") %>
<div class="admin-devices admin_psge_right">
  <div class="devices">
    <div class="admin_list_devices">
      <%= render "list_devices" %>
    </div>
  </div>
</div>
<% if can? :destroy, @device %>
  <div class="new-device">
    <%= link_to new_admin_device_path do %>
      <button class="btn btn-primary"><%= t "device.new" %></button>
    <% end %>
    <%= link_to t("device.export"),
      admin_devices_path(format: Settings.server.export_format),
      class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/devices/new.html.erb
<div class="admin-devices">
  <h3><%= t "device.device_content_title" %></h3>
  <div class="devices">
    <%= simple_form_for [:admin, @device], wrapper: :horizontal_form,
      html: {class: "new-device"} do |f| %>

      <%= f.input :name, label: t("device.device_name"),
        input_html: {class: "form-control"} %>

      <%= f.input :informations, label: t("device.informations"),
        input_html: {class: "form-control"} %>

      <%= f.input :status, label: t("device.status"),
        input_html: {class: "form-control"} %>

      <% if current_user.position == User.user_positions[:admin] %>
        <%= f.input :workspace_id, collection: @base_support.get_workspaces,
          label_method: :name, value_method: :id, include_blank: false,
          label: t("device.workspace"),
          input_html: {class: "form-control"} %>
      <% else %>
        <%= f.hidden_field :workspace_id,
          value: current_user.group.workspace_id,
          input_html: {class: "form-control"} %>
      <% end -%>

      <%= f.input :category_id, collection: @base_support.get_categories,
        label_method: :name, value_method: :id, include_blank: false,
        label: t("device.category"), input_html: {class: "form-control"} %>

      <%= f.input :thumnail, as: :file, label: t("device.image") %>

      <%= f.button :submit, t("device.btn_new_device"), class: "btn btn-primary" %>

    <% end -%>
  </div>
</div>
<div class="import-device">
  <h4><b><%= t "device.import_title" %><b></h4>
  <%= form_tag admin_devices_path, method: :post, multipart: true do %>
    <%= file_field_tag :import_file %>
    <%= hidden_field_tag :import %>
    <br/>
    <%= submit_tag t "device.import" %>
  <% end %>
</div>