config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  resources :devices

  post "new_cart", to: "carts#create"
  delete "destroy_cart", to: "carts#destroy"

  devise_for :users, skip: :registrations
  as :user do
    get "users/edit", to: "devise/registrations#edit",
      as: "edit_user_registration"
    put "users", to: "devise/registrations#update", as: "user_registration"
  end

  resources :users, only: :show
  resources :messages
  resources :devices
  resources :borrow_devices

  namespace :admin do
   resources :borrow_devices
   resources :devices
  end

  mount ActionCable.server => "/cable"
end

app/views/layouts/_cart.html.erb
<h4><%= t "device.list_borrowed" %></h4>
<table class="table table-bordered">
  <tr>
    <th class="td_small"><%= t "device.thumnail" %></th>
    <th><%= t "device.name_device" %></th>
    <th><%= t "device.delete" %></th>
  </tr>
  <% if get_list_devices.present? %>
    <%= render partial: "layouts/cart_item", collection: get_list_devices %>
  <% end -%>
</table>

app/views/layouts/_cart_item.html.erb
<tr>
  <td class="td_small">
    <%= image_tag cart_item.thumnail, class: "img-responsive cart_image" %>
  </td>
  <td>
    <b><%= link_to cart_item.name, device_path(cart_item.id) %></b>
  </td>
  <td>
    <%= link_to destroy_cart_path(device_id: cart_item.id),
      method: :delete, remote: true do %>
      <span class="glyphicon glyphicon-remove"></span>
    <% end -%>
  </td>
</tr>

app/views/layouts/_footer.html.erb
<section id="contact_us">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">
          <%= t "home.title_home_contact" %>
        </h2>
        <hr class="primary">
        <p><%= t "home.description_home_contact" %></p>
      </div>
      <div class="col-lg-4 col-lg-offset-2 text-center">
        <i class="fa fa-phone fa-3x sr-contact"></i>
        <p><%= t "home.phone_home_contact" %></p>
      </div>
      <div class="col-lg-4 text-center">
        <i class="fa fa-envelope-o fa-3x sr-contact"></i>
        <p>
          <%= t "home.email_home_contact" %>
        </p>
      </div>
    </div>
  </div>
</section>
<% if user_signed_in? %>
  <%= render partial: "messages/form", locals: {message: Message.new} %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="header-content">
    <div class="header-content-inner">
      <h1 id="homeHeading"><%= t "home.title_home" %></h1>
      <hr>
      <div class="input-group search_form home_search">
        <%= form_tag "", method: :get do %>
          <%= text_field_tag :search, params[:search],
            placeholder: t("home.search_device"), class: "form-control input-lg" %>
          <span class="input-group-btn">
            <%= submit_tag t "home.search", class: "btn btn-info btn-lg"  %>
          </span>
        <% end %>
      </div>
      <%= link_to t("sessions.signin"), new_user_session_path,
        class: "btn btn-primary login" %>
    </div>
  </div>
</header>

app/views/layouts/_menu_admin.html.erb
<div class="menu-admin">
  <ul>
    <li>
      <%= link_to t("admin_menu.menu"), "#", class: "active menu-admin-link" %>
    </li>
    <li>
      <%= link_to t("admin_menu.workspace"), "#", class: "menu-admin-link" %>
    </li>
    <li>
      <%= link_to t("admin_menu.group"), "#", class: "menu-admin-link" %>
    </li>
    <li>
      <%= link_to t("admin_menu.category"), "#", class: "menu-admin-link" %>
    </li>
    <li>
      <%= link_to t("admin_menu.user"), "#", class: "menu-admin-link" %>
    </li>
    <li>
      <%= link_to t("admin_menu.device"), "#", class: "menu-admin-link" %>
    </li>
    <li>
      <%= link_to t("admin_menu.borrow"), admin_borrow_devices_path,
        class: "menu-admin-link" %>
    </li>
  </ul>
</div>

app/views/layouts/_nav.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed">
        <span class="sr-only"></span><i class="fa fa-bars"></i>
      </button>
      <%= link_to image_tag("logo.png"), root_path, class: "logo_f" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("menu.home"), root_path %></li>
        <li><%= link_to t("menu.devices"), devices_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown notification">
            <%= link_to "", class: "dropdown-toggle", id: "noti-count",
              data: {toggle: "dropdown"},
              aria: {haspopup: "true", "data-id": current_user.id,
              expanded: "false"} do %>
              <span class="fa fa-globe"></span>
              <span class="badge badge-danger"
                id="badge-dange_<%= current_user.id%>"
                data-noti-count="<%= current_user.notifications.num_not_check %>">
                <%= current_user.notifications.num_not_check %>
              </span>
              <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu dropdown-notification scrollable-menu"
              id="show_notifition_<%= current_user.id %>" >
              <% if current_user.notifications.any?  %>
                <% current_user.notifications.each do |notification| %>
                  <li class="read_<%= "#{notification.read}" %>">
                    <%= link_to "#{notification.notifications}",
                    notification.link, "data-id": notification.id %>
                    <span>
                      <%= time_ago_in_words(notification.created_at)
                        + t("menu.ago") %>
                    </span>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </li>
          <li class="dropdown">
            <a class="menu_drop" data-toggle="dropdown">
              <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("menu.profile"), current_user %></li>
              <li><%= link_to t("menu.settings"),
                edit_user_registration_path %></li>
              <li><%= link_to t("menu.my_borrowing_devices"), "" %></li>
              <li>
                <%= link_to t("sessions.signout"), destroy_user_session_path,
                  method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "admin.dashboard" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <div class="container">
      <div class="show_error">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      </div>
    </div>
    <%= render "layouts/nav" %>
    <div class="container margin_top">
      <div class="menu col-md-3">
        <%= render "layouts/menu_admin" %>
      </div>
      <div class="content col-md-9">
        <%= yield %>
      </div>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "home.tittle" %></title>
    <%= favicon_link_tag "favicon.ico" %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= action_cable_meta_tag %>
  </head>
  <body>
    <div class="container">
      <div class="show_error">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      </div>
    </div>
    <%= render "layouts/nav" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>